package org.hraink.futures.ctp.thostftdcuserapistruct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcSyncingTradingAccountField extends StructObject {
	public CThostFtdcSyncingTradingAccountField() {
		super();
	}
	/// \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801
	@Array({11}) 
	@Field(0) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 0);
	}
	/// \u6295\u8d44\u8005\u5e10\u53f7
	@Array({13}) 
	@Field(1) 
	public Pointer<Byte > AccountID() {
		return this.io.getPointerField(this, 1);
	}
	/// \u4e0a\u6b21\u8d28\u62bc\u91d1\u989d
	@Field(2) 
	public double PreMortgage() {
		return this.io.getDoubleField(this, 2);
	}
	/// \u4e0a\u6b21\u8d28\u62bc\u91d1\u989d
	@Field(2) 
	public CThostFtdcSyncingTradingAccountField PreMortgage(double PreMortgage) {
		this.io.setDoubleField(this, 2, PreMortgage);
		return this;
	}
	/// \u4e0a\u6b21\u4fe1\u7528\u989d\u5ea6
	@Field(3) 
	public double PreCredit() {
		return this.io.getDoubleField(this, 3);
	}
	/// \u4e0a\u6b21\u4fe1\u7528\u989d\u5ea6
	@Field(3) 
	public CThostFtdcSyncingTradingAccountField PreCredit(double PreCredit) {
		this.io.setDoubleField(this, 3, PreCredit);
		return this;
	}
	/// \u4e0a\u6b21\u5b58\u6b3e\u989d
	@Field(4) 
	public double PreDeposit() {
		return this.io.getDoubleField(this, 4);
	}
	/// \u4e0a\u6b21\u5b58\u6b3e\u989d
	@Field(4) 
	public CThostFtdcSyncingTradingAccountField PreDeposit(double PreDeposit) {
		this.io.setDoubleField(this, 4, PreDeposit);
		return this;
	}
	/// \u4e0a\u6b21\u7ed3\u7b97\u51c6\u5907\u91d1
	@Field(5) 
	public double PreBalance() {
		return this.io.getDoubleField(this, 5);
	}
	/// \u4e0a\u6b21\u7ed3\u7b97\u51c6\u5907\u91d1
	@Field(5) 
	public CThostFtdcSyncingTradingAccountField PreBalance(double PreBalance) {
		this.io.setDoubleField(this, 5, PreBalance);
		return this;
	}
	/// \u4e0a\u6b21\u5360\u7528\u7684\u4fdd\u8bc1\u91d1
	@Field(6) 
	public double PreMargin() {
		return this.io.getDoubleField(this, 6);
	}
	/// \u4e0a\u6b21\u5360\u7528\u7684\u4fdd\u8bc1\u91d1
	@Field(6) 
	public CThostFtdcSyncingTradingAccountField PreMargin(double PreMargin) {
		this.io.setDoubleField(this, 6, PreMargin);
		return this;
	}
	/// \u5229\u606f\u57fa\u6570
	@Field(7) 
	public double InterestBase() {
		return this.io.getDoubleField(this, 7);
	}
	/// \u5229\u606f\u57fa\u6570
	@Field(7) 
	public CThostFtdcSyncingTradingAccountField InterestBase(double InterestBase) {
		this.io.setDoubleField(this, 7, InterestBase);
		return this;
	}
	/// \u5229\u606f\u6536\u5165
	@Field(8) 
	public double Interest() {
		return this.io.getDoubleField(this, 8);
	}
	/// \u5229\u606f\u6536\u5165
	@Field(8) 
	public CThostFtdcSyncingTradingAccountField Interest(double Interest) {
		this.io.setDoubleField(this, 8, Interest);
		return this;
	}
	/// \u5165\u91d1\u91d1\u989d
	@Field(9) 
	public double Deposit() {
		return this.io.getDoubleField(this, 9);
	}
	/// \u5165\u91d1\u91d1\u989d
	@Field(9) 
	public CThostFtdcSyncingTradingAccountField Deposit(double Deposit) {
		this.io.setDoubleField(this, 9, Deposit);
		return this;
	}
	/// \u51fa\u91d1\u91d1\u989d
	@Field(10) 
	public double Withdraw() {
		return this.io.getDoubleField(this, 10);
	}
	/// \u51fa\u91d1\u91d1\u989d
	@Field(10) 
	public CThostFtdcSyncingTradingAccountField Withdraw(double Withdraw) {
		this.io.setDoubleField(this, 10, Withdraw);
		return this;
	}
	/// \u51bb\u7ed3\u7684\u4fdd\u8bc1\u91d1
	@Field(11) 
	public double FrozenMargin() {
		return this.io.getDoubleField(this, 11);
	}
	/// \u51bb\u7ed3\u7684\u4fdd\u8bc1\u91d1
	@Field(11) 
	public CThostFtdcSyncingTradingAccountField FrozenMargin(double FrozenMargin) {
		this.io.setDoubleField(this, 11, FrozenMargin);
		return this;
	}
	/// \u51bb\u7ed3\u7684\u8d44\u91d1
	@Field(12) 
	public double FrozenCash() {
		return this.io.getDoubleField(this, 12);
	}
	/// \u51bb\u7ed3\u7684\u8d44\u91d1
	@Field(12) 
	public CThostFtdcSyncingTradingAccountField FrozenCash(double FrozenCash) {
		this.io.setDoubleField(this, 12, FrozenCash);
		return this;
	}
	/// \u51bb\u7ed3\u7684\u624b\u7eed\u8d39
	@Field(13) 
	public double FrozenCommission() {
		return this.io.getDoubleField(this, 13);
	}
	/// \u51bb\u7ed3\u7684\u624b\u7eed\u8d39
	@Field(13) 
	public CThostFtdcSyncingTradingAccountField FrozenCommission(double FrozenCommission) {
		this.io.setDoubleField(this, 13, FrozenCommission);
		return this;
	}
	/// \u5f53\u524d\u4fdd\u8bc1\u91d1\u603b\u989d
	@Field(14) 
	public double CurrMargin() {
		return this.io.getDoubleField(this, 14);
	}
	/// \u5f53\u524d\u4fdd\u8bc1\u91d1\u603b\u989d
	@Field(14) 
	public CThostFtdcSyncingTradingAccountField CurrMargin(double CurrMargin) {
		this.io.setDoubleField(this, 14, CurrMargin);
		return this;
	}
	/// \u8d44\u91d1\u5dee\u989d
	@Field(15) 
	public double CashIn() {
		return this.io.getDoubleField(this, 15);
	}
	/// \u8d44\u91d1\u5dee\u989d
	@Field(15) 
	public CThostFtdcSyncingTradingAccountField CashIn(double CashIn) {
		this.io.setDoubleField(this, 15, CashIn);
		return this;
	}
	/// \u624b\u7eed\u8d39
	@Field(16) 
	public double Commission() {
		return this.io.getDoubleField(this, 16);
	}
	/// \u624b\u7eed\u8d39
	@Field(16) 
	public CThostFtdcSyncingTradingAccountField Commission(double Commission) {
		this.io.setDoubleField(this, 16, Commission);
		return this;
	}
	/// \u5e73\u4ed3\u76c8\u4e8f
	@Field(17) 
	public double CloseProfit() {
		return this.io.getDoubleField(this, 17);
	}
	/// \u5e73\u4ed3\u76c8\u4e8f
	@Field(17) 
	public CThostFtdcSyncingTradingAccountField CloseProfit(double CloseProfit) {
		this.io.setDoubleField(this, 17, CloseProfit);
		return this;
	}
	/// \u6301\u4ed3\u76c8\u4e8f
	@Field(18) 
	public double PositionProfit() {
		return this.io.getDoubleField(this, 18);
	}
	/// \u6301\u4ed3\u76c8\u4e8f
	@Field(18) 
	public CThostFtdcSyncingTradingAccountField PositionProfit(double PositionProfit) {
		this.io.setDoubleField(this, 18, PositionProfit);
		return this;
	}
	/// \u671f\u8d27\u7ed3\u7b97\u51c6\u5907\u91d1
	@Field(19) 
	public double Balance() {
		return this.io.getDoubleField(this, 19);
	}
	/// \u671f\u8d27\u7ed3\u7b97\u51c6\u5907\u91d1
	@Field(19) 
	public CThostFtdcSyncingTradingAccountField Balance(double Balance) {
		this.io.setDoubleField(this, 19, Balance);
		return this;
	}
	/// \u53ef\u7528\u8d44\u91d1
	@Field(20) 
	public double Available() {
		return this.io.getDoubleField(this, 20);
	}
	/// \u53ef\u7528\u8d44\u91d1
	@Field(20) 
	public CThostFtdcSyncingTradingAccountField Available(double Available) {
		this.io.setDoubleField(this, 20, Available);
		return this;
	}
	/// \u53ef\u53d6\u8d44\u91d1
	@Field(21) 
	public double WithdrawQuota() {
		return this.io.getDoubleField(this, 21);
	}
	/// \u53ef\u53d6\u8d44\u91d1
	@Field(21) 
	public CThostFtdcSyncingTradingAccountField WithdrawQuota(double WithdrawQuota) {
		this.io.setDoubleField(this, 21, WithdrawQuota);
		return this;
	}
	/// \u57fa\u672c\u51c6\u5907\u91d1
	@Field(22) 
	public double Reserve() {
		return this.io.getDoubleField(this, 22);
	}
	/// \u57fa\u672c\u51c6\u5907\u91d1
	@Field(22) 
	public CThostFtdcSyncingTradingAccountField Reserve(double Reserve) {
		this.io.setDoubleField(this, 22, Reserve);
		return this;
	}
	/// \u4ea4\u6613\u65e5
	@Array({9}) 
	@Field(23) 
	public Pointer<Byte > TradingDay() {
		return this.io.getPointerField(this, 23);
	}
	/// \u7ed3\u7b97\u7f16\u53f7
	@Field(24) 
	public int SettlementID() {
		return this.io.getIntField(this, 24);
	}
	/// \u7ed3\u7b97\u7f16\u53f7
	@Field(24) 
	public CThostFtdcSyncingTradingAccountField SettlementID(int SettlementID) {
		this.io.setIntField(this, 24, SettlementID);
		return this;
	}
	/// \u4fe1\u7528\u989d\u5ea6
	@Field(25) 
	public double Credit() {
		return this.io.getDoubleField(this, 25);
	}
	/// \u4fe1\u7528\u989d\u5ea6
	@Field(25) 
	public CThostFtdcSyncingTradingAccountField Credit(double Credit) {
		this.io.setDoubleField(this, 25, Credit);
		return this;
	}
	/// \u8d28\u62bc\u91d1\u989d
	@Field(26) 
	public double Mortgage() {
		return this.io.getDoubleField(this, 26);
	}
	/// \u8d28\u62bc\u91d1\u989d
	@Field(26) 
	public CThostFtdcSyncingTradingAccountField Mortgage(double Mortgage) {
		this.io.setDoubleField(this, 26, Mortgage);
		return this;
	}
	/// \u4ea4\u6613\u6240\u4fdd\u8bc1\u91d1
	@Field(27) 
	public double ExchangeMargin() {
		return this.io.getDoubleField(this, 27);
	}
	/// \u4ea4\u6613\u6240\u4fdd\u8bc1\u91d1
	@Field(27) 
	public CThostFtdcSyncingTradingAccountField ExchangeMargin(double ExchangeMargin) {
		this.io.setDoubleField(this, 27, ExchangeMargin);
		return this;
	}
	/// \u6295\u8d44\u8005\u4ea4\u5272\u4fdd\u8bc1\u91d1
	@Field(28) 
	public double DeliveryMargin() {
		return this.io.getDoubleField(this, 28);
	}
	/// \u6295\u8d44\u8005\u4ea4\u5272\u4fdd\u8bc1\u91d1
	@Field(28) 
	public CThostFtdcSyncingTradingAccountField DeliveryMargin(double DeliveryMargin) {
		this.io.setDoubleField(this, 28, DeliveryMargin);
		return this;
	}
	/// \u4ea4\u6613\u6240\u4ea4\u5272\u4fdd\u8bc1\u91d1
	@Field(29) 
	public double ExchangeDeliveryMargin() {
		return this.io.getDoubleField(this, 29);
	}
	/// \u4ea4\u6613\u6240\u4ea4\u5272\u4fdd\u8bc1\u91d1
	@Field(29) 
	public CThostFtdcSyncingTradingAccountField ExchangeDeliveryMargin(double ExchangeDeliveryMargin) {
		this.io.setDoubleField(this, 29, ExchangeDeliveryMargin);
		return this;
	}
	public CThostFtdcSyncingTradingAccountField(Pointer pointer) {
		super(pointer);
	}
}
