package org.hraink.futures.ctp.thostftdcuserapistruct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcEWarrantOffsetField extends StructObject {
	public CThostFtdcEWarrantOffsetField() {
		super();
	}
	/// \u4ea4\u6613\u65e5\u671f
	@Array({9}) 
	@Field(0) 
	public Pointer<Byte > TradingDay() {
		return this.io.getPointerField(this, 0);
	}
	/// \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801
	@Array({11}) 
	@Field(1) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 1);
	}
	/// \u6295\u8d44\u8005\u4ee3\u7801
	@Array({13}) 
	@Field(2) 
	public Pointer<Byte > InvestorID() {
		return this.io.getPointerField(this, 2);
	}
	/// \u4ea4\u6613\u6240\u4ee3\u7801
	@Array({9}) 
	@Field(3) 
	public Pointer<Byte > ExchangeID() {
		return this.io.getPointerField(this, 3);
	}
	/// \u5408\u7ea6\u4ee3\u7801
	@Array({31}) 
	@Field(4) 
	public Pointer<Byte > InstrumentID() {
		return this.io.getPointerField(this, 4);
	}
	/// \u4e70\u5356\u65b9\u5411
	@Field(5) 
	public byte Direction() {
		return this.io.getByteField(this, 5);
	}
	/// \u4e70\u5356\u65b9\u5411
	@Field(5) 
	public CThostFtdcEWarrantOffsetField Direction(byte Direction) {
		this.io.setByteField(this, 5, Direction);
		return this;
	}
	/// \u6295\u673a\u5957\u4fdd\u6807\u5fd7
	@Field(6) 
	public byte HedgeFlag() {
		return this.io.getByteField(this, 6);
	}
	/// \u6295\u673a\u5957\u4fdd\u6807\u5fd7
	@Field(6) 
	public CThostFtdcEWarrantOffsetField HedgeFlag(byte HedgeFlag) {
		this.io.setByteField(this, 6, HedgeFlag);
		return this;
	}
	/// \u6570\u91cf
	@Field(7) 
	public int Volume() {
		return this.io.getIntField(this, 7);
	}
	/// \u6570\u91cf
	@Field(7) 
	public CThostFtdcEWarrantOffsetField Volume(int Volume) {
		this.io.setIntField(this, 7, Volume);
		return this;
	}
	public CThostFtdcEWarrantOffsetField(Pointer pointer) {
		super(pointer);
	}
}
