package org.hraink.futures.ctp.thostftdcuserapistruct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcRspUserLoginField extends StructObject {
	public CThostFtdcRspUserLoginField() {
		super();
	}
	/// \u4ea4\u6613\u65e5
	@Array({9}) 
	@Field(0) 
	public Pointer<Byte > TradingDay() {
		return this.io.getPointerField(this, 0);
	}
	/// \u767b\u5f55\u6210\u529f\u65f6\u95f4
	@Array({9}) 
	@Field(1) 
	public Pointer<Byte > LoginTime() {
		return this.io.getPointerField(this, 1);
	}
	/// \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801
	@Array({11}) 
	@Field(2) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 2);
	}
	/// \u7528\u6237\u4ee3\u7801
	@Array({16}) 
	@Field(3) 
	public Pointer<Byte > UserID() {
		return this.io.getPointerField(this, 3);
	}
	/// \u4ea4\u6613\u7cfb\u7edf\u540d\u79f0
	@Array({41}) 
	@Field(4) 
	public Pointer<Byte > SystemName() {
		return this.io.getPointerField(this, 4);
	}
	/// \u524d\u7f6e\u7f16\u53f7
	@Field(5) 
	public int FrontID() {
		return this.io.getIntField(this, 5);
	}
	/// \u524d\u7f6e\u7f16\u53f7
	@Field(5) 
	public CThostFtdcRspUserLoginField FrontID(int FrontID) {
		this.io.setIntField(this, 5, FrontID);
		return this;
	}
	/// \u4f1a\u8bdd\u7f16\u53f7
	@Field(6) 
	public int SessionID() {
		return this.io.getIntField(this, 6);
	}
	/// \u4f1a\u8bdd\u7f16\u53f7
	@Field(6) 
	public CThostFtdcRspUserLoginField SessionID(int SessionID) {
		this.io.setIntField(this, 6, SessionID);
		return this;
	}
	/// \u6700\u5927\u62a5\u5355\u5f15\u7528
	@Array({13}) 
	@Field(7) 
	public Pointer<Byte > MaxOrderRef() {
		return this.io.getPointerField(this, 7);
	}
	/// \u4e0a\u671f\u6240\u65f6\u95f4
	@Array({9}) 
	@Field(8) 
	public Pointer<Byte > SHFETime() {
		return this.io.getPointerField(this, 8);
	}
	/// \u5927\u5546\u6240\u65f6\u95f4
	@Array({9}) 
	@Field(9) 
	public Pointer<Byte > DCETime() {
		return this.io.getPointerField(this, 9);
	}
	/// \u90d1\u5546\u6240\u65f6\u95f4
	@Array({9}) 
	@Field(10) 
	public Pointer<Byte > CZCETime() {
		return this.io.getPointerField(this, 10);
	}
	/// \u4e2d\u91d1\u6240\u65f6\u95f4
	@Array({9}) 
	@Field(11) 
	public Pointer<Byte > FFEXTime() {
		return this.io.getPointerField(this, 11);
	}
	public CThostFtdcRspUserLoginField(Pointer pointer) {
		super(pointer);
	}
}
