package org.hraink.futures.ctp.thostftdcuserapistruct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcTransferFutureToBankRspField extends StructObject {
	public CThostFtdcTransferFutureToBankRspField() {
		super();
	}
	/// \u54cd\u5e94\u4ee3\u7801
	@Array({5}) 
	@Field(0) 
	public Pointer<Byte > RetCode() {
		return this.io.getPointerField(this, 0);
	}
	/// \u54cd\u5e94\u4fe1\u606f
	@Array({129}) 
	@Field(1) 
	public Pointer<Byte > RetInfo() {
		return this.io.getPointerField(this, 1);
	}
	/// \u8d44\u91d1\u8d26\u6237
	@Array({13}) 
	@Field(2) 
	public Pointer<Byte > FutureAccount() {
		return this.io.getPointerField(this, 2);
	}
	/// \u8f6c\u5e10\u91d1\u989d
	@Field(3) 
	public double TradeAmt() {
		return this.io.getDoubleField(this, 3);
	}
	/// \u8f6c\u5e10\u91d1\u989d
	@Field(3) 
	public CThostFtdcTransferFutureToBankRspField TradeAmt(double TradeAmt) {
		this.io.setDoubleField(this, 3, TradeAmt);
		return this;
	}
	/// \u5e94\u6536\u5ba2\u6237\u624b\u7eed\u8d39
	@Field(4) 
	public double CustFee() {
		return this.io.getDoubleField(this, 4);
	}
	/// \u5e94\u6536\u5ba2\u6237\u624b\u7eed\u8d39
	@Field(4) 
	public CThostFtdcTransferFutureToBankRspField CustFee(double CustFee) {
		this.io.setDoubleField(this, 4, CustFee);
		return this;
	}
	/// \u5e01\u79cd
	@Array({4}) 
	@Field(5) 
	public Pointer<Byte > CurrencyCode() {
		return this.io.getPointerField(this, 5);
	}
	public CThostFtdcTransferFutureToBankRspField(Pointer pointer) {
		super(pointer);
	}
}
