package org.hraink.futures.ctp.thostftdcuserapistruct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcMarketDataUpdateTimeField extends StructObject {
	public CThostFtdcMarketDataUpdateTimeField() {
		super();
	}
	/// \u5408\u7ea6\u4ee3\u7801
	@Array({31}) 
	@Field(0) 
	public Pointer<Byte > InstrumentID() {
		return this.io.getPointerField(this, 0);
	}
	/// \u6700\u540e\u4fee\u6539\u65f6\u95f4
	@Array({9}) 
	@Field(1) 
	public Pointer<Byte > UpdateTime() {
		return this.io.getPointerField(this, 1);
	}
	/// \u6700\u540e\u4fee\u6539\u6beb\u79d2
	@Field(2) 
	public int UpdateMillisec() {
		return this.io.getIntField(this, 2);
	}
	/// \u6700\u540e\u4fee\u6539\u6beb\u79d2
	@Field(2) 
	public CThostFtdcMarketDataUpdateTimeField UpdateMillisec(int UpdateMillisec) {
		this.io.setIntField(this, 2, UpdateMillisec);
		return this;
	}
	public CThostFtdcMarketDataUpdateTimeField(Pointer pointer) {
		super(pointer);
	}
}
