package com.fick.smd.hibernate.formbean.stockbean;

// Generated 2013-4-3 9:51:23 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Stockdealdetail generated by hbm2java
 */
public class StockDealDetail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7421635476073494611L;
	private Integer id;
	private String stockcode;
	private int dealtype;
	private float dealprice;
	private int dealNum;
	private float dealcost;
	private Date dealdt;

	public StockDealDetail() {
	}

	public StockDealDetail(String stockcode, int dealtype, float dealprice, int dealNum, float dealcost, Date dealdt) {
		this.stockcode = stockcode;
		this.dealtype = dealtype;
		this.dealprice = dealprice;
		this.dealNum = dealNum;
		this.dealcost = dealcost;
		this.dealdt = dealdt;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getStockcode() {
		return this.stockcode;
	}

	public void setStockcode(String stockcode) {
		this.stockcode = stockcode;
	}

	public int getDealtype() {
		return this.dealtype;
	}

	public void setDealtype(int dealtype) {
		this.dealtype = dealtype;
	}

	public float getDealprice() {
		return this.dealprice;
	}

	public void setDealprice(float dealprice) {
		this.dealprice = dealprice;
	}

	public int getDealNum() {
		return this.dealNum;
	}

	public void setDealNum(int dealNum) {
		this.dealNum = dealNum;
	}

	public float getDealcost() {
		return this.dealcost;
	}

	public void setDealcost(float dealcost) {
		this.dealcost = dealcost;
	}

	public Date getDealdt() {
		return this.dealdt;
	}

	public void setDealdt(Date dealdt) {
		this.dealdt = dealdt;
	}

}
