package com.fick.smd.hibernate.formbean.esperbean;

// Generated 2013-2-26 10:40:36 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Epldef generated by hbm2java
 */
public class EplDef implements java.io.Serializable {

	private Integer id;
	private String eplname;
	private String eplrun;
	private String eplshow;
	private Integer type;
	private String listenerclassname;
	private Integer eplst;
	private String remark;
	private Date updatedt;

	public EplDef() {
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getEplname() {
		return this.eplname;
	}

	public void setEplname(String eplname) {
		this.eplname = eplname;
	}

	public String getEplrun() {
		return this.eplrun;
	}

	public void setEplrun(String eplrun) {
		this.eplrun = eplrun;
	}

	public String getEplshow() {
		return this.eplshow;
	}

	public void setEplshow(String eplshow) {
		this.eplshow = eplshow;
	}

	public Integer getEplst() {
		return this.eplst;
	}

	public void setEplst(Integer eplst) {
		this.eplst = eplst;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Date getUpdatedt() {
		return this.updatedt;
	}

	public void setUpdatedt(Date updatedt) {
		this.updatedt = updatedt;
	}

	public String getListenerclassname() {
		return listenerclassname;
	}

	public void setListenerclassname(String listenerclassname) {
		this.listenerclassname = listenerclassname;
	}

	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

}
