package cn.com.webxml;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-02-25T11:01:30.382+08:00
 * Generated source version: 2.7.3
 * 
 */
@WebService(targetNamespace = "http://WebXml.com.cn/", name = "ChinaStockWebServiceHttpPost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ChinaStockWebServiceHttpPost {

    /**
     * <br /><h3>获得中国股票GIF分时走势图字节数组</h3><p>输入参数：theStockCode = 股票代号，如：sh000001； 返回数据：股票GIF分时走势图字节数组。<br /><strong>字节流到图片可以参考以下方法</strong>（.NET vb）：<br />HttpContext.Current.Response.Cache.SetCacheability(System.Web.HttpCacheability.NoCache) '不缓存<br />HttpContext.Current.Response.ClearContent()<br />HttpContext.Current.Response.ContentType = "image/Gif"<br />HttpContext.Current.Response.BinaryWrite(Ary) 'Ary 图片字节数组<br />HttpContext.Current.Response.End()</p><br />
     */
    @WebResult(name = "base64Binary", targetNamespace = "http://WebXml.com.cn/", partName = "Body")
    @WebMethod
    public byte[] getStockImageByteByCode(
        @WebParam(partName = "theStockCode", name = "theStockCode", targetNamespace = "http://WebXml.com.cn/")
        java.lang.String theStockCode
    );

    /**
     * <br /><h3>直接获得中国股票GIF日/周/月 K 线图（545*300pixel/72dpi）</h3><p>输入参数：theStockCode = 股票代号，如：sh000001；theType = K 线图类型（D：日[默认]、W：周、M：月），返回数据：股票GIF日 K 线图。</p><br />
     */
    @WebMethod(operationName = "getStockImage_kByCode")
    public void getStockImageKByCode(
        @WebParam(partName = "theStockCode", name = "theStockCode", targetNamespace = "http://WebXml.com.cn/")
        java.lang.String theStockCode,
        @WebParam(partName = "theType", name = "theType", targetNamespace = "http://WebXml.com.cn/")
        java.lang.String theType
    );

    /**
     * <br /><h3>获得中国股票GIF日/周/月 K 线图字节数组</h3><p>输入参数：theStockCode = 股票代号，如：sh000001；theType = K 线图类型（D：日[默认]、W：周、M：月），返回数据：股票GIF日 K 线图字节数组。</p><br />
     */
    @WebResult(name = "base64Binary", targetNamespace = "http://WebXml.com.cn/", partName = "Body")
    @WebMethod(operationName = "getStockImage_kByteByCode")
    public byte[] getStockImageKByteByCode(
        @WebParam(partName = "theStockCode", name = "theStockCode", targetNamespace = "http://WebXml.com.cn/")
        java.lang.String theStockCode,
        @WebParam(partName = "theType", name = "theType", targetNamespace = "http://WebXml.com.cn/")
        java.lang.String theType
    );

    /**
     * <br /><h3>直接获得中国股票GIF分时走势图（545*300pixel/72dpi）</h3><p>输入参数：theStockCode = 股票代号，如：sh000001； 返回数据：股票GIF分时走势图。</p><br />
     */
    @WebMethod
    public void getStockImageByCode(
        @WebParam(partName = "theStockCode", name = "theStockCode", targetNamespace = "http://WebXml.com.cn/")
        java.lang.String theStockCode
    );

    /**
     * <br /><h3>获得中国股票及时行情 String()</h3><p>输入参数：theStockCode = 股票代号，如：sh000001； 返回数据：一个一维字符串数组 String(24)，结构为：String(0)股票代号、String(1)股票名称、String(2)行情时间、String(3)最新价（元）、String(4)昨收盘（元）、String(5)今开盘（元）、String(6)涨跌额（元）、String(7)最低（元）、String(8)最高（元）、String(9)涨跌幅（%）、String(10)成交量（手）、String(11)成交额（万元）、String(12)竞买价（元）、String(13)竞卖价（元）、String(14)委比（%）、String(15)-String(19)买一 - 买五（元）/手、String(20)-String(24)卖一 - 卖五（元）/手。</p><br />
     */
    @WebResult(name = "ArrayOfString", targetNamespace = "http://WebXml.com.cn/", partName = "Body")
    @WebMethod
    public ArrayOfString getStockInfoByCode(
        @WebParam(partName = "theStockCode", name = "theStockCode", targetNamespace = "http://WebXml.com.cn/")
        java.lang.String theStockCode
    );
}
