package cn.com.webxml;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * <a href="http://www.webxml.com.cn/" target="_blank">WebXml.com.cn</a> <strong>中国股票行情数据 WEB 服务（支持深圳和上海股市的全部基金、债券和股票）</strong>，数据即时更新。输出GIF分时走势图、日/周/月 K 线图、及时行情数据（股票名称、行情时间、最新价、昨收盘、今开盘、涨跌额、最低、最高、涨跌幅、成交量、成交额、竞买价、竞卖价、委比、买一 - 买五、卖一 - 卖五）。此中国股票行情数据 WEB 服务仅作为用户获取信息之目的，并不构成投资建议。<a href="http://www.webxml.com.cn/" target="_blank">WebXml.com.cn</a> 和/或其各供应商不为本页面提供信息的错误、残缺、延迟或因依靠此信息所采取的任何行动负责。<strong>市场有风险，投资需谨慎</strong>。<br />此中国股票行情数据Web Services请不要用于任何商业目的，若有需要请<a href="http://www.webxml.com.cn/zh_cn/contact_us.aspx" target="_blank">联系我们</a>，欢迎技术交流。 QQ：8409035<br /><strong>使用本站 WEB 服务请注明或链接本站：http://www.webxml.com.cn/ 感谢大家的支持</strong>！<br /><br /><span style="color:#D20000;"><strong>股票输入注意事项</strong>：因上海股票和深圳股票在代号上有重叠，所以在输入上海股票请在代号前加 SH，深圳加 SZ（不区分大小写），例：上证指数 sh000001，深发展A sz000001。如不输入股票代号默认上证指数 sh000001</span><br /><br />&nbsp;
 *
 * This class was generated by Apache CXF 2.7.3
 * 2013-02-25T11:01:30.404+08:00
 * Generated source version: 2.7.3
 * 
 */
@WebServiceClient(name = "ChinaStockWebService", 
                  wsdlLocation = "http://www.webxml.com.cn/WebServices/ChinaStockWebService.asmx?WSDL",
                  targetNamespace = "http://WebXml.com.cn/") 
public class ChinaStockWebService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://WebXml.com.cn/", "ChinaStockWebService");
    public final static QName ChinaStockWebServiceSoap12 = new QName("http://WebXml.com.cn/", "ChinaStockWebServiceSoap12");
    public final static QName ChinaStockWebServiceSoap = new QName("http://WebXml.com.cn/", "ChinaStockWebServiceSoap");
    public final static QName ChinaStockWebServiceHttpPost = new QName("http://WebXml.com.cn/", "ChinaStockWebServiceHttpPost");
    public final static QName ChinaStockWebServiceHttpGet = new QName("http://WebXml.com.cn/", "ChinaStockWebServiceHttpGet");
    static {
        URL url = null;
        try {
            url = new URL("http://www.webxml.com.cn/WebServices/ChinaStockWebService.asmx?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ChinaStockWebService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://www.webxml.com.cn/WebServices/ChinaStockWebService.asmx?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public ChinaStockWebService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ChinaStockWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ChinaStockWebService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns ChinaStockWebServiceSoap
     */
    @WebEndpoint(name = "ChinaStockWebServiceSoap12")
    public ChinaStockWebServiceSoap getChinaStockWebServiceSoap12() {
        return super.getPort(ChinaStockWebServiceSoap12, ChinaStockWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ChinaStockWebServiceSoap
     */
    @WebEndpoint(name = "ChinaStockWebServiceSoap12")
    public ChinaStockWebServiceSoap getChinaStockWebServiceSoap12(WebServiceFeature... features) {
        return super.getPort(ChinaStockWebServiceSoap12, ChinaStockWebServiceSoap.class, features);
    }
    /**
     *
     * @return
     *     returns ChinaStockWebServiceSoap
     */
    @WebEndpoint(name = "ChinaStockWebServiceSoap")
    public ChinaStockWebServiceSoap getChinaStockWebServiceSoap() {
        return super.getPort(ChinaStockWebServiceSoap, ChinaStockWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ChinaStockWebServiceSoap
     */
    @WebEndpoint(name = "ChinaStockWebServiceSoap")
    public ChinaStockWebServiceSoap getChinaStockWebServiceSoap(WebServiceFeature... features) {
        return super.getPort(ChinaStockWebServiceSoap, ChinaStockWebServiceSoap.class, features);
    }
    /**
     *
     * @return
     *     returns ChinaStockWebServiceHttpPost
     */
    @WebEndpoint(name = "ChinaStockWebServiceHttpPost")
    public ChinaStockWebServiceHttpPost getChinaStockWebServiceHttpPost() {
        return super.getPort(ChinaStockWebServiceHttpPost, ChinaStockWebServiceHttpPost.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ChinaStockWebServiceHttpPost
     */
    @WebEndpoint(name = "ChinaStockWebServiceHttpPost")
    public ChinaStockWebServiceHttpPost getChinaStockWebServiceHttpPost(WebServiceFeature... features) {
        return super.getPort(ChinaStockWebServiceHttpPost, ChinaStockWebServiceHttpPost.class, features);
    }
    /**
     *
     * @return
     *     returns ChinaStockWebServiceHttpGet
     */
    @WebEndpoint(name = "ChinaStockWebServiceHttpGet")
    public ChinaStockWebServiceHttpGet getChinaStockWebServiceHttpGet() {
        return super.getPort(ChinaStockWebServiceHttpGet, ChinaStockWebServiceHttpGet.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ChinaStockWebServiceHttpGet
     */
    @WebEndpoint(name = "ChinaStockWebServiceHttpGet")
    public ChinaStockWebServiceHttpGet getChinaStockWebServiceHttpGet(WebServiceFeature... features) {
        return super.getPort(ChinaStockWebServiceHttpGet, ChinaStockWebServiceHttpGet.class, features);
    }

}
