package org.hraink.futures.ctp.thostftdcuserapistruct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcTransferQryDetailRspField extends StructObject {
	public CThostFtdcTransferQryDetailRspField() {
		super();
	}
	/// \u4ea4\u6613\u65e5\u671f
	@Array({9}) 
	@Field(0) 
	public Pointer<Byte > TradeDate() {
		return this.io.getPointerField(this, 0);
	}
	/// \u4ea4\u6613\u65f6\u95f4
	@Array({9}) 
	@Field(1) 
	public Pointer<Byte > TradeTime() {
		return this.io.getPointerField(this, 1);
	}
	/// \u4ea4\u6613\u4ee3\u7801
	@Array({7}) 
	@Field(2) 
	public Pointer<Byte > TradeCode() {
		return this.io.getPointerField(this, 2);
	}
	/// \u671f\u8d27\u6d41\u6c34\u53f7
	@Field(3) 
	public int FutureSerial() {
		return this.io.getIntField(this, 3);
	}
	/// \u671f\u8d27\u6d41\u6c34\u53f7
	@Field(3) 
	public CThostFtdcTransferQryDetailRspField FutureSerial(int FutureSerial) {
		this.io.setIntField(this, 3, FutureSerial);
		return this;
	}
	/// \u671f\u8d27\u516c\u53f8\u4ee3\u7801
	@Array({11}) 
	@Field(4) 
	public Pointer<Byte > FutureID() {
		return this.io.getPointerField(this, 4);
	}
	/// \u8d44\u91d1\u5e10\u53f7
	@Array({22}) 
	@Field(5) 
	public Pointer<Byte > FutureAccount() {
		return this.io.getPointerField(this, 5);
	}
	/// \u94f6\u884c\u6d41\u6c34\u53f7
	@Field(6) 
	public int BankSerial() {
		return this.io.getIntField(this, 6);
	}
	/// \u94f6\u884c\u6d41\u6c34\u53f7
	@Field(6) 
	public CThostFtdcTransferQryDetailRspField BankSerial(int BankSerial) {
		this.io.setIntField(this, 6, BankSerial);
		return this;
	}
	/// \u94f6\u884c\u4ee3\u7801
	@Array({4}) 
	@Field(7) 
	public Pointer<Byte > BankID() {
		return this.io.getPointerField(this, 7);
	}
	/// \u94f6\u884c\u5206\u4e2d\u5fc3\u4ee3\u7801
	@Array({5}) 
	@Field(8) 
	public Pointer<Byte > BankBrchID() {
		return this.io.getPointerField(this, 8);
	}
	/// \u94f6\u884c\u8d26\u53f7
	@Array({41}) 
	@Field(9) 
	public Pointer<Byte > BankAccount() {
		return this.io.getPointerField(this, 9);
	}
	/// \u8bc1\u4ef6\u53f7\u7801
	@Array({21}) 
	@Field(10) 
	public Pointer<Byte > CertCode() {
		return this.io.getPointerField(this, 10);
	}
	/// \u8d27\u5e01\u4ee3\u7801
	@Array({4}) 
	@Field(11) 
	public Pointer<Byte > CurrencyCode() {
		return this.io.getPointerField(this, 11);
	}
	/// \u53d1\u751f\u91d1\u989d
	@Field(12) 
	public double TxAmount() {
		return this.io.getDoubleField(this, 12);
	}
	/// \u53d1\u751f\u91d1\u989d
	@Field(12) 
	public CThostFtdcTransferQryDetailRspField TxAmount(double TxAmount) {
		this.io.setDoubleField(this, 12, TxAmount);
		return this;
	}
	/// \u6709\u6548\u6807\u5fd7
	@Field(13) 
	public byte Flag() {
		return this.io.getByteField(this, 13);
	}
	/// \u6709\u6548\u6807\u5fd7
	@Field(13) 
	public CThostFtdcTransferQryDetailRspField Flag(byte Flag) {
		this.io.setByteField(this, 13, Flag);
		return this;
	}
	public CThostFtdcTransferQryDetailRspField(Pointer pointer) {
		super(pointer);
	}
}
