package org.hraink.futures.ctp.thostftdcuserapistruct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcTransferBankField extends StructObject {
	public CThostFtdcTransferBankField() {
		super();
	}
	/// \u94f6\u884c\u4ee3\u7801
	@Array({4}) 
	@Field(0) 
	public Pointer<Byte > BankID() {
		return this.io.getPointerField(this, 0);
	}
	/// \u94f6\u884c\u5206\u4e2d\u5fc3\u4ee3\u7801
	@Array({5}) 
	@Field(1) 
	public Pointer<Byte > BankBrchID() {
		return this.io.getPointerField(this, 1);
	}
	/// \u94f6\u884c\u540d\u79f0
	@Array({101}) 
	@Field(2) 
	public Pointer<Byte > BankName() {
		return this.io.getPointerField(this, 2);
	}
	/// \u662f\u5426\u6d3b\u8dc3
	@Field(3) 
	public int IsActive() {
		return this.io.getIntField(this, 3);
	}
	/// \u662f\u5426\u6d3b\u8dc3
	@Field(3) 
	public CThostFtdcTransferBankField IsActive(int IsActive) {
		this.io.setIntField(this, 3, IsActive);
		return this;
	}
	public CThostFtdcTransferBankField(Pointer pointer) {
		super(pointer);
	}
}
