package org.hraink.futures.ctp.thostftdcuserapistruct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcTransferSerialField extends StructObject {
	public CThostFtdcTransferSerialField() {
		super();
	}
	/// \u5e73\u53f0\u6d41\u6c34\u53f7
	@Field(0) 
	public int PlateSerial() {
		return this.io.getIntField(this, 0);
	}
	/// \u5e73\u53f0\u6d41\u6c34\u53f7
	@Field(0) 
	public CThostFtdcTransferSerialField PlateSerial(int PlateSerial) {
		this.io.setIntField(this, 0, PlateSerial);
		return this;
	}
	/// \u4ea4\u6613\u53d1\u8d77\u65b9\u65e5\u671f
	@Array({9}) 
	@Field(1) 
	public Pointer<Byte > TradeDate() {
		return this.io.getPointerField(this, 1);
	}
	/// \u4ea4\u6613\u65e5\u671f
	@Array({9}) 
	@Field(2) 
	public Pointer<Byte > TradingDay() {
		return this.io.getPointerField(this, 2);
	}
	/// \u4ea4\u6613\u65f6\u95f4
	@Array({9}) 
	@Field(3) 
	public Pointer<Byte > TradeTime() {
		return this.io.getPointerField(this, 3);
	}
	/// \u4ea4\u6613\u4ee3\u7801
	@Array({7}) 
	@Field(4) 
	public Pointer<Byte > TradeCode() {
		return this.io.getPointerField(this, 4);
	}
	/// \u4f1a\u8bdd\u7f16\u53f7
	@Field(5) 
	public int SessionID() {
		return this.io.getIntField(this, 5);
	}
	/// \u4f1a\u8bdd\u7f16\u53f7
	@Field(5) 
	public CThostFtdcTransferSerialField SessionID(int SessionID) {
		this.io.setIntField(this, 5, SessionID);
		return this;
	}
	/// \u94f6\u884c\u7f16\u7801
	@Array({4}) 
	@Field(6) 
	public Pointer<Byte > BankID() {
		return this.io.getPointerField(this, 6);
	}
	/// \u94f6\u884c\u5206\u652f\u673a\u6784\u7f16\u7801
	@Array({5}) 
	@Field(7) 
	public Pointer<Byte > BankBranchID() {
		return this.io.getPointerField(this, 7);
	}
	/// \u94f6\u884c\u5e10\u53f7\u7c7b\u578b
	@Field(8) 
	public byte BankAccType() {
		return this.io.getByteField(this, 8);
	}
	/// \u94f6\u884c\u5e10\u53f7\u7c7b\u578b
	@Field(8) 
	public CThostFtdcTransferSerialField BankAccType(byte BankAccType) {
		this.io.setByteField(this, 8, BankAccType);
		return this;
	}
	/// \u94f6\u884c\u5e10\u53f7
	@Array({41}) 
	@Field(9) 
	public Pointer<Byte > BankAccount() {
		return this.io.getPointerField(this, 9);
	}
	/// \u94f6\u884c\u6d41\u6c34\u53f7
	@Array({13}) 
	@Field(10) 
	public Pointer<Byte > BankSerial() {
		return this.io.getPointerField(this, 10);
	}
	/// \u671f\u8d27\u516c\u53f8\u7f16\u7801
	@Array({11}) 
	@Field(11) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 11);
	}
	/// \u671f\u5546\u5206\u652f\u673a\u6784\u4ee3\u7801
	@Array({31}) 
	@Field(12) 
	public Pointer<Byte > BrokerBranchID() {
		return this.io.getPointerField(this, 12);
	}
	/// \u671f\u8d27\u516c\u53f8\u5e10\u53f7\u7c7b\u578b
	@Field(13) 
	public byte FutureAccType() {
		return this.io.getByteField(this, 13);
	}
	/// \u671f\u8d27\u516c\u53f8\u5e10\u53f7\u7c7b\u578b
	@Field(13) 
	public CThostFtdcTransferSerialField FutureAccType(byte FutureAccType) {
		this.io.setByteField(this, 13, FutureAccType);
		return this;
	}
	/// \u6295\u8d44\u8005\u5e10\u53f7
	@Array({13}) 
	@Field(14) 
	public Pointer<Byte > AccountID() {
		return this.io.getPointerField(this, 14);
	}
	/// \u6295\u8d44\u8005\u4ee3\u7801
	@Array({13}) 
	@Field(15) 
	public Pointer<Byte > InvestorID() {
		return this.io.getPointerField(this, 15);
	}
	/// \u671f\u8d27\u516c\u53f8\u6d41\u6c34\u53f7
	@Field(16) 
	public int FutureSerial() {
		return this.io.getIntField(this, 16);
	}
	/// \u671f\u8d27\u516c\u53f8\u6d41\u6c34\u53f7
	@Field(16) 
	public CThostFtdcTransferSerialField FutureSerial(int FutureSerial) {
		this.io.setIntField(this, 16, FutureSerial);
		return this;
	}
	/// \u8bc1\u4ef6\u7c7b\u578b
	@Field(17) 
	public byte IdCardType() {
		return this.io.getByteField(this, 17);
	}
	/// \u8bc1\u4ef6\u7c7b\u578b
	@Field(17) 
	public CThostFtdcTransferSerialField IdCardType(byte IdCardType) {
		this.io.setByteField(this, 17, IdCardType);
		return this;
	}
	/// \u8bc1\u4ef6\u53f7\u7801
	@Array({51}) 
	@Field(18) 
	public Pointer<Byte > IdentifiedCardNo() {
		return this.io.getPointerField(this, 18);
	}
	/// \u5e01\u79cd\u4ee3\u7801
	@Array({4}) 
	@Field(19) 
	public Pointer<Byte > CurrencyID() {
		return this.io.getPointerField(this, 19);
	}
	/// \u4ea4\u6613\u91d1\u989d
	@Field(20) 
	public double TradeAmount() {
		return this.io.getDoubleField(this, 20);
	}
	/// \u4ea4\u6613\u91d1\u989d
	@Field(20) 
	public CThostFtdcTransferSerialField TradeAmount(double TradeAmount) {
		this.io.setDoubleField(this, 20, TradeAmount);
		return this;
	}
	/// \u5e94\u6536\u5ba2\u6237\u8d39\u7528
	@Field(21) 
	public double CustFee() {
		return this.io.getDoubleField(this, 21);
	}
	/// \u5e94\u6536\u5ba2\u6237\u8d39\u7528
	@Field(21) 
	public CThostFtdcTransferSerialField CustFee(double CustFee) {
		this.io.setDoubleField(this, 21, CustFee);
		return this;
	}
	/// \u5e94\u6536\u671f\u8d27\u516c\u53f8\u8d39\u7528
	@Field(22) 
	public double BrokerFee() {
		return this.io.getDoubleField(this, 22);
	}
	/// \u5e94\u6536\u671f\u8d27\u516c\u53f8\u8d39\u7528
	@Field(22) 
	public CThostFtdcTransferSerialField BrokerFee(double BrokerFee) {
		this.io.setDoubleField(this, 22, BrokerFee);
		return this;
	}
	/// \u6709\u6548\u6807\u5fd7
	@Field(23) 
	public byte AvailabilityFlag() {
		return this.io.getByteField(this, 23);
	}
	/// \u6709\u6548\u6807\u5fd7
	@Field(23) 
	public CThostFtdcTransferSerialField AvailabilityFlag(byte AvailabilityFlag) {
		this.io.setByteField(this, 23, AvailabilityFlag);
		return this;
	}
	/// \u64cd\u4f5c\u5458
	@Array({17}) 
	@Field(24) 
	public Pointer<Byte > OperatorCode() {
		return this.io.getPointerField(this, 24);
	}
	/// \u65b0\u94f6\u884c\u5e10\u53f7
	@Array({41}) 
	@Field(25) 
	public Pointer<Byte > BankNewAccount() {
		return this.io.getPointerField(this, 25);
	}
	/// \u9519\u8bef\u4ee3\u7801
	@Field(26) 
	public int ErrorID() {
		return this.io.getIntField(this, 26);
	}
	/// \u9519\u8bef\u4ee3\u7801
	@Field(26) 
	public CThostFtdcTransferSerialField ErrorID(int ErrorID) {
		this.io.setIntField(this, 26, ErrorID);
		return this;
	}
	/// \u9519\u8bef\u4fe1\u606f
	@Array({81}) 
	@Field(27) 
	public Pointer<Byte > ErrorMsg() {
		return this.io.getPointerField(this, 27);
	}
	public CThostFtdcTransferSerialField(Pointer pointer) {
		super(pointer);
	}
}
