package org.hraink.futures.ctp.thostftdcuserapistruct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcTradingAccountPasswordUpdateField extends StructObject {
	public CThostFtdcTradingAccountPasswordUpdateField() {
		super();
	}
	/// \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801
	@Array({11}) 
	@Field(0) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 0);
	}
	/// \u6295\u8d44\u8005\u5e10\u53f7
	@Array({13}) 
	@Field(1) 
	public Pointer<Byte > AccountID() {
		return this.io.getPointerField(this, 1);
	}
	/// \u539f\u6765\u7684\u53e3\u4ee4
	@Array({41}) 
	@Field(2) 
	public Pointer<Byte > OldPassword() {
		return this.io.getPointerField(this, 2);
	}
	/// \u65b0\u7684\u53e3\u4ee4
	@Array({41}) 
	@Field(3) 
	public Pointer<Byte > NewPassword() {
		return this.io.getPointerField(this, 3);
	}
	public CThostFtdcTradingAccountPasswordUpdateField(Pointer pointer) {
		super(pointer);
	}
}
