package org.hraink.futures.ctp.thostftdcuserapistruct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcLinkManField extends StructObject {
	public CThostFtdcLinkManField() {
		super();
	}
	/// \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801
	@Array({11}) 
	@Field(0) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 0);
	}
	/// \u6295\u8d44\u8005\u4ee3\u7801
	@Array({13}) 
	@Field(1) 
	public Pointer<Byte > InvestorID() {
		return this.io.getPointerField(this, 1);
	}
	/// \u8054\u7cfb\u4eba\u7c7b\u578b
	@Field(2) 
	public byte PersonType() {
		return this.io.getByteField(this, 2);
	}
	/// \u8054\u7cfb\u4eba\u7c7b\u578b
	@Field(2) 
	public CThostFtdcLinkManField PersonType(byte PersonType) {
		this.io.setByteField(this, 2, PersonType);
		return this;
	}
	/// \u8bc1\u4ef6\u7c7b\u578b
	@Field(3) 
	public byte IdentifiedCardType() {
		return this.io.getByteField(this, 3);
	}
	/// \u8bc1\u4ef6\u7c7b\u578b
	@Field(3) 
	public CThostFtdcLinkManField IdentifiedCardType(byte IdentifiedCardType) {
		this.io.setByteField(this, 3, IdentifiedCardType);
		return this;
	}
	/// \u8bc1\u4ef6\u53f7\u7801
	@Array({51}) 
	@Field(4) 
	public Pointer<Byte > IdentifiedCardNo() {
		return this.io.getPointerField(this, 4);
	}
	/// \u540d\u79f0
	@Array({81}) 
	@Field(5) 
	public Pointer<Byte > PersonName() {
		return this.io.getPointerField(this, 5);
	}
	/// \u8054\u7cfb\u7535\u8bdd
	@Array({41}) 
	@Field(6) 
	public Pointer<Byte > Telephone() {
		return this.io.getPointerField(this, 6);
	}
	/// \u901a\u8baf\u5730\u5740
	@Array({101}) 
	@Field(7) 
	public Pointer<Byte > Address() {
		return this.io.getPointerField(this, 7);
	}
	/// \u90ae\u653f\u7f16\u7801
	@Array({7}) 
	@Field(8) 
	public Pointer<Byte > ZipCode() {
		return this.io.getPointerField(this, 8);
	}
	/// \u4f18\u5148\u7ea7
	@Field(9) 
	public int Priority() {
		return this.io.getIntField(this, 9);
	}
	/// \u4f18\u5148\u7ea7
	@Field(9) 
	public CThostFtdcLinkManField Priority(int Priority) {
		this.io.setIntField(this, 9, Priority);
		return this;
	}
	public CThostFtdcLinkManField(Pointer pointer) {
		super(pointer);
	}
}
