package org.hraink.futures.ctp.thostftdcuserapistruct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcQryUserSessionField extends StructObject {
	public CThostFtdcQryUserSessionField() {
		super();
	}
	/// \u524d\u7f6e\u7f16\u53f7
	@Field(0) 
	public int FrontID() {
		return this.io.getIntField(this, 0);
	}
	/// \u524d\u7f6e\u7f16\u53f7
	@Field(0) 
	public CThostFtdcQryUserSessionField FrontID(int FrontID) {
		this.io.setIntField(this, 0, FrontID);
		return this;
	}
	/// \u4f1a\u8bdd\u7f16\u53f7
	@Field(1) 
	public int SessionID() {
		return this.io.getIntField(this, 1);
	}
	/// \u4f1a\u8bdd\u7f16\u53f7
	@Field(1) 
	public CThostFtdcQryUserSessionField SessionID(int SessionID) {
		this.io.setIntField(this, 1, SessionID);
		return this;
	}
	/// \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801
	@Array({11}) 
	@Field(2) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 2);
	}
	/// \u7528\u6237\u4ee3\u7801
	@Array({16}) 
	@Field(3) 
	public Pointer<Byte > UserID() {
		return this.io.getPointerField(this, 3);
	}
	public CThostFtdcQryUserSessionField(Pointer pointer) {
		super(pointer);
	}
}
