package org.hraink.futures.ctp.thostftdcuserapistruct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcBrokerTradingParamsField extends StructObject {
	public CThostFtdcBrokerTradingParamsField() {
		super();
	}
	/// \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801
	@Array({11}) 
	@Field(0) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 0);
	}
	/// \u6295\u8d44\u8005\u4ee3\u7801
	@Array({13}) 
	@Field(1) 
	public Pointer<Byte > InvestorID() {
		return this.io.getPointerField(this, 1);
	}
	/// \u4fdd\u8bc1\u91d1\u4ef7\u683c\u7c7b\u578b
	@Field(2) 
	public byte MarginPriceType() {
		return this.io.getByteField(this, 2);
	}
	/// \u4fdd\u8bc1\u91d1\u4ef7\u683c\u7c7b\u578b
	@Field(2) 
	public CThostFtdcBrokerTradingParamsField MarginPriceType(byte MarginPriceType) {
		this.io.setByteField(this, 2, MarginPriceType);
		return this;
	}
	/// \u76c8\u4e8f\u7b97\u6cd5
	@Field(3) 
	public byte Algorithm() {
		return this.io.getByteField(this, 3);
	}
	/// \u76c8\u4e8f\u7b97\u6cd5
	@Field(3) 
	public CThostFtdcBrokerTradingParamsField Algorithm(byte Algorithm) {
		this.io.setByteField(this, 3, Algorithm);
		return this;
	}
	/// \u53ef\u7528\u662f\u5426\u5305\u542b\u5e73\u4ed3\u76c8\u5229
	@Field(4) 
	public byte AvailIncludeCloseProfit() {
		return this.io.getByteField(this, 4);
	}
	/// \u53ef\u7528\u662f\u5426\u5305\u542b\u5e73\u4ed3\u76c8\u5229
	@Field(4) 
	public CThostFtdcBrokerTradingParamsField AvailIncludeCloseProfit(byte AvailIncludeCloseProfit) {
		this.io.setByteField(this, 4, AvailIncludeCloseProfit);
		return this;
	}
	public CThostFtdcBrokerTradingParamsField(Pointer pointer) {
		super(pointer);
	}
}
