package org.hraink.futures.ctp.thostftdcuserapistruct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class CThostFtdcExchangeMarginRateField extends StructObject {
	public CThostFtdcExchangeMarginRateField() {
		super();
	}
	/// \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801
	@Array({11}) 
	@Field(0) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 0);
	}
	/// \u5408\u7ea6\u4ee3\u7801
	@Array({31}) 
	@Field(1) 
	public Pointer<Byte > InstrumentID() {
		return this.io.getPointerField(this, 1);
	}
	/// \u6295\u673a\u5957\u4fdd\u6807\u5fd7
	@Field(2) 
	public byte HedgeFlag() {
		return this.io.getByteField(this, 2);
	}
	/// \u6295\u673a\u5957\u4fdd\u6807\u5fd7
	@Field(2) 
	public CThostFtdcExchangeMarginRateField HedgeFlag(byte HedgeFlag) {
		this.io.setByteField(this, 2, HedgeFlag);
		return this;
	}
	/// \u591a\u5934\u4fdd\u8bc1\u91d1\u7387
	@Field(3) 
	public double LongMarginRatioByMoney() {
		return this.io.getDoubleField(this, 3);
	}
	/// \u591a\u5934\u4fdd\u8bc1\u91d1\u7387
	@Field(3) 
	public CThostFtdcExchangeMarginRateField LongMarginRatioByMoney(double LongMarginRatioByMoney) {
		this.io.setDoubleField(this, 3, LongMarginRatioByMoney);
		return this;
	}
	/// \u591a\u5934\u4fdd\u8bc1\u91d1\u8d39
	@Field(4) 
	public double LongMarginRatioByVolume() {
		return this.io.getDoubleField(this, 4);
	}
	/// \u591a\u5934\u4fdd\u8bc1\u91d1\u8d39
	@Field(4) 
	public CThostFtdcExchangeMarginRateField LongMarginRatioByVolume(double LongMarginRatioByVolume) {
		this.io.setDoubleField(this, 4, LongMarginRatioByVolume);
		return this;
	}
	/// \u7a7a\u5934\u4fdd\u8bc1\u91d1\u7387
	@Field(5) 
	public double ShortMarginRatioByMoney() {
		return this.io.getDoubleField(this, 5);
	}
	/// \u7a7a\u5934\u4fdd\u8bc1\u91d1\u7387
	@Field(5) 
	public CThostFtdcExchangeMarginRateField ShortMarginRatioByMoney(double ShortMarginRatioByMoney) {
		this.io.setDoubleField(this, 5, ShortMarginRatioByMoney);
		return this;
	}
	/// \u7a7a\u5934\u4fdd\u8bc1\u91d1\u8d39
	@Field(6) 
	public double ShortMarginRatioByVolume() {
		return this.io.getDoubleField(this, 6);
	}
	/// \u7a7a\u5934\u4fdd\u8bc1\u91d1\u8d39
	@Field(6) 
	public CThostFtdcExchangeMarginRateField ShortMarginRatioByVolume(double ShortMarginRatioByVolume) {
		this.io.setDoubleField(this, 6, ShortMarginRatioByVolume);
		return this;
	}
	public CThostFtdcExchangeMarginRateField(Pointer pointer) {
		super(pointer);
	}
}
