package com.fick.smd.hibernate.formbean.stockbean;

// Generated 2013-2-25 13:11:44 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Stockdef generated by hbm2java
 */
public class StockDef implements java.io.Serializable {

	private Integer id;
	private String stockcode;
	private String stockname;
	private Integer stockst;
	private Integer type;
	private String remark;
	private Date updatedt;

	public StockDef() {
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getStockcode() {
		return this.stockcode;
	}

	public void setStockcode(String stockcode) {
		this.stockcode = stockcode;
	}

	public String getStockname() {
		return this.stockname;
	}

	public void setStockname(String stockname) {
		this.stockname = stockname;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Date getUpdatedt() {
		return this.updatedt;
	}

	public void setUpdatedt(Date updatedt) {
		this.updatedt = updatedt;
	}

	public Integer getStockst() {
		return stockst;
	}

	public void setStockst(Integer stockst) {
		this.stockst = stockst;
	}

}
