package com.fick.smd.hibernate.formbean.sysbean;

// Generated 2013-2-21 15:58:16 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Syschangelog generated by hbm2java
 */
public class SysChangeLog implements java.io.Serializable {

	private Integer id;
	private String version;
	private String author;
	private String operator;
	private String remark;
	private Date updatedt;

	public SysChangeLog() {
	}

	public SysChangeLog(String author, String operator, String remark, Date updatedt) {
		this.author = author;
		this.operator = operator;
		this.remark = remark;
		this.updatedt = updatedt;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Date getUpdatedt() {
		return this.updatedt;
	}

	public void setUpdatedt(Date updatedt) {
		this.updatedt = updatedt;
	}

}
